version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: turbo-next
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turbo_next_dev
    ports:
      - "45432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 