/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API
 * turbo-next api definitions
 * OpenAPI spec version: v1
 */
import { z as zod } from "zod";

export const getCurrentUserResponse = zod.object({
  id: zod.string().describe("ラベル"),
  name: zod.string().describe("名前"),
});
