/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API
 * turbo-next api definitions
 * OpenAPI spec version: v1
 */
import type { Context, Env } from 'hono';

export type GetCurrentUserContext<E extends Env = any> = Context<E, '/api/current-user'>