import "@/app/_styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { TooltipProvider } from "@/app/_components/ui/tooltip";
import { JotaiProvider } from "../_providers/jotaiProvider";
import { ReactQueryProvider } from "../_providers/reactQueryProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <JotaiProvider>
          <ReactQueryProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </ReactQueryProvider>
        </JotaiProvider>
      </body>
    </html>
  );
};

export default RootLayout;
