/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API
 * turbo-next api definitions
 * OpenAPI spec version: v1
 */
import { Hono } from "hono";
import { getCurrentUserHandlers } from "./routes/current-user/current-user.handlers";

const app = new Hono();

app.get("/api/current-user", ...getCurrentUserHandlers);

export default app;
