/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API
 * turbo-next api definitions
 * OpenAPI spec version: v1
 */
export type IdName = {
  /** ラベル */
  id: number;
  /** 名前 */
  name: string;
};

export type CustomError = {
  message: string;
  errors: ErrorDetail[];
};

export type ErrorDetail = {
  /** エラーになったプロパティ */
  key: string;
  /** エラーメッセージ */
  message: string;
};
